language: scala
scala:
  - 2.10.6
  - 2.11.11
jdk:
  - openjdk7
  - oraclejdk7
  - oraclejdk8
matrix:
  include:
  - scala: 2.12.2
    jdk: oraclejdk8
install:
  - pip install --user codecov
script:
  - sbt ++$TRAVIS_SCALA_VERSION clean coverage test coverageReport scalastyle;
  - codecov
